### ISSUE TITLE
dramatiq-abort does not abort DQ jobs

### ISSUE THREAD

**Issue by cchacholiades** [Flared/dramatiq-abort#3] opened 2021-03-18 11:47 UTC
Hi, I am trying to use this package as I need to be able to cancel / abort tasks in my dramatiq delayed queue. 

```
from dramatiq import get_broker
from dramatiq_abort import Abortable, backends, abort

def cancel_task(self, task_id):
    """
    Cancels a REDIS task given a task_id
    """
    redis_client = redis.Redis(host=settings.REDIS_LOCAL, port=6379, db=0)

    abortable = Abortable(backend=backends.RedisBackend(client=redis_client))
    get_broker().add_middleware(abortable)

    abort(task_id)
```

I am not sure if this is the correct way to use it. The above code doesn't produce any errors, nor it aborts the scheduled task. Any ideas? 

Update: 

- My test scenario has two scheduled jobs back to back, both have the same ETA. Before scheduling the 2nd job the above `cancel_task` get's called so that the 1st job is cancelled and the 2nd job should now be the one to be executed. 
- I have tested the above code and it works for as long as there is sufficient time in between these two scheduled jobs, let's say a minute. If the ETA differs scheduled job 1 will get skipped; If the jobs are both running at the same ETA, dramatiq executes both of the jobs and ignores the fact the first has been marked as aborted.

**Comment by isra17** [comment] 2021-03-18 14:04
Hum, can you by any chance create a test case that replicate the issue? 

There's a few test case existing here: https://github.com/Flared/dramatiq-abort/blob/master/tests/test_abortable.py

**Comment by cchacholiades** [comment] 2021-03-18 14:08
@isra17 Thanks you for replying. I think I have just resolved the issue now... so I am using django, I think I had to instantiate django-abort before importing dramatiq in my tasks.py file. That's what I did, and now I can see jobs being skipped..  

Can you please delete this issue?

**Comment by cchacholiades** [comment] 2021-04-21 17:57
Hi @isra17, I am re-opening this as we are still facing this issue. I can see jobs executing which should have been marked as skipped. 

Unfortunately, I cannot reproduce the issue on my local environment but it happens a lot and randomly when in production. I use a procfile to `rundramatiq` as a worker. I wonder if between deployments this stops / starts workers; and therefore would that have anything to do with it?

**Comment by isra17** [comment] 2021-04-23 13:40
I see you closed again, found a fix/not a bug?

**Comment by cchacholiades** [comment] 2021-04-23 14:08
@isra17 Unfortunately no, I have not resolved this yet. 

I am unsure if this is a bug or if I am doing something wrong. When I test in my local environment everything seems to work but when I deploy it, it doesn't. Therefore, I thought I should close this issue and asked my question on [stackoverflow](https://stackoverflow.com/questions/67227761/django-dramatiq-dramatiq-abort-issue-with-elasticache-redis) where it seemed more appropriate.

**Comment by cchacholiades** [comment] 2021-04-27 13:11
@isra17 I am having trouble identifying the root cause of the problem. At this point I think I exhausted all of possible scenarios;  At some point I thought the issue has to do with the way I deploy my app however that's not the case. Question: Is there a number of how many tasks can be aborted consecutively?

**Comment by isra17** [comment] 2021-04-27 17:07
This shouldn't. The way it works it stores the task id in Redis and then the working check everynow and then if one of the incoming or running task has been flagged to be aborted by checking Redis for the task id. Kind of like:

```python
is_aborted = Redis.pop(task_id, False)
```

One way to debug could be to check in Redis if the key are there and/or add some logging to the code to check what is being polled in Redis and what are the results.

**Comment by isra17** [comment] 2021-04-27 17:10
The code is somewhat simple: https://github.com/Flared/dramatiq-abort/blob/master/src/dramatiq_abort/backends/redis.py

You should be able to add some log easily in `poll` / `wait_many`.

**Comment by cchacholiades** [comment] 2021-04-27 17:24
It is very strange, I can see sometimes the jobs being aborted and other times not. No cohesion which makes it difficult to debug. And we actually rely on the fact that tasks which have been set multiple times are cancelling each other and only the job that has been scheduled last will execute.

**Comment by cchacholiades** [comment] 2021-04-28 10:58
@isra17 I added some prints in `poll` to check what is happening. It seems for some reason it doesn't properly set the abort but the code between these two functions is identical in terms of scheduled / abort logic. 


```
#  JOB1 was skipped correctly.
b'abort:024956ae-0843-4dc5-9d43-ad9676437a81'
b'x'
[2021-04-28 11:20:56,933] [PID 99014] [Thread-11] [dramatiq.worker.WorkerThread] [WARNING] Message test_abort_job('some message') was skipped.

# JOB1 scheduled last, executed correctly
b'abort:4f0e3f5f-bd2f-4d7f-b8a6-5172cddbe8bc'
None

# JOB2, below message should be executed 
b'abort:80b03509-1351-4450-ab93-ff472b73b592'
None

#  JOB2, below message should be skipped, but still executed
b'abort:cd5f643d-00ef-4ac2-b164-359ad7e46f89'
None
```

**Comment by cchacholiades** [comment] 2021-04-28 15:02
@isra17 I created a sample django project with how I've set things up and instruction to reproduce. Can you please have a look? https://github.com/cchacholiades/djdabortbug

**Comment by isra17** [comment] 2021-04-28 19:40
You mean, [it stops working after 90000ms](https://github.com/Flared/dramatiq-abort/blob/master/src/dramatiq_abort/middleware.py#L54) ?

**Comment by isra17** [comment] 2021-04-28 19:43
I would probably add a kwarg `abort_ttl` to the `abort` function to allow setting a higher value for your use case. Do you want to create a PR for that?

**Comment by cchacholiades** [comment] 2021-04-28 23:11
@isra17 Awesome stuff thank you! And yes I created a PR already let me know if this does it.

**Comment by cchacholiades** [comment] 2021-04-29 19:34
@isra17 maybe can you link the PR to this issue and close it?

**Comment by isra17** [comment] 2021-04-29 20:39
Fixed by #8

**Closed by isra17** 2021-04-29 20:39 UTC
Labels: bug

**Comment by Kastakin** [comment] 2022-04-11 07:26
Is there a limit on the TTL accepted by Redis? 

In my application I have a queue where each job can take various hours to complete and multiple jobs can be scheduled so I needed a TTL that was as big as possible. At first I tried utilizing `sys.maxsize` as the `abort_ttl` value but it didn't work and jobs were not aborted correctly. Setting manually the `abort_ttl` solved the issue but I just wanted to understand if there was a limit in Redis worth documenting.

**Comment by isra17** [comment] 2022-04-12 14:40
Seems like Redis accept a max int value (2**31-1). I will accept a PR that document the limit or raise an exception if over it (In the redis backend).

**Comment by Kastakin** [comment] 2022-04-12 17:15
> Seems like Redis accept a max int value (2**31-1). I will accept a PR that document the limit or raise an exception if over it (In the redis backend).

I will try to contribute in the coming days, thanks for checking out the issue
